### ISSUE TITLE
not an issue but advice

### ISSUE THREAD

**Issue by zainullahk** [sanjeevstunner/Vayu-Releases#1]
instead of making an unofficial pe you should just co-maintain pixelos (its based on pixelexperience but way better)
cause with you then pixelos could be the best rom (cause pe devs dont accept many changes)

**Comment by sanjeevstunner** [comment]
Actually, I love PE the best and am using it as my daily driver. I've seen some comments like this in XDA too, thanks for reaching me. 
But, here's the issue. Alison won't listen to me and requesting him to make me his co-maintainer, means I'm making a fool of myself. 

But also, if say I ask pixel OS dev, there'll be a contradiction between our choices, so for now I'm better off with maintaining the ROMs all alone. I now support PPUI, Elixir, PEX and that's it. People seem to love it my way, and I don't want to spoil it for them. 

My PE is just for me, and I upload it to git and post in XDA just for fun. Also, people like the existing ROMs as it is. I don't want to ruin it for them as well. I'll put some thoughts on it. I'd like to maintain  Pixel OS and Proton AOSP. They are both my current favs that I am not building 😂 

Anyways, Thanks Again for reaching me. Have a great day ❤

**Comment by zainullahk** [comment]
i hope you can at the least ask pixelos devs to become a co maintainer
it would be so good to have a rom with all the stuff that your rom has
mixed with pixelos which is already amazing
the combo would be the best of the best rom

**Comment by zainullahk** [comment]
also btw remove  adaptive charging 
x3 pro has buggy pmic it will brick with adaptive charging

**Comment by zainullahk** [comment]
very important update @sanjeevstunner 
pixelos dev for x3 pro no longer has the phone and will no longer develop!
i hope you can continue it
if you want to maintain pixelos (which would be 1000x better)
apply here https://github.com/PixelOS-Pixelish/official_devices

**Comment by zainullahk** [comment]
this is sad to see  my fav rom get discontinued for vayu
btw if you start maintaing it dont enable adaptive charging cause of the buggy pmic
thanks again!  
this is the perfect chance to maintain (the dev announced today that they sold  the phone)
